[package]
name = "secret-ink"
version = "0.1.0"
edition = "2024"


[dependencies]
fastrand = "2.3"
ab_glyph = "0.2"
image = "0.25"
imageproc = "0.25"
pulldown-cmark = "0.13"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
textwrap = { version = "0.16", features = ["hyphenation"] }
