[package]
name = "secret-ink"
version = "0.1.0"
edition = "2024"


[dependencies]
cosmic-text = "0.14"
env_logger = "0.11"
fontdb = "0.23"
log = "0.4"
softbuffer = "0.4"
tiny-skia = "0.11"
unicode-segmentation = "1.7"
winit = "0.29"
fastrand = "2.3.0"
