# config.toml
page_width = 2048
page_height = 2048
margin_top = 200
margin_bottom = 200
margin_left = 100
margin_right = 100

default_font = "fonts/Special_Elite/SpecialElite-Regular.ttf"
heading_font = "fonts/Pica/Pica.ttf"
stamp_font = "fonts/stampwriter_kit/STAMPWRITER-KIT.ttf"
font_size = 32.0
heading_size = 64.0
stamp_size = 72.0

jitter_px = 2.0
blur_sigma = 0.3
ink_opacity = 0.95

redaction_marker = "=="
stamp_marker = "!!"

paper_albedo = "paper/CC0-Texture-Paper01/PaperAlbedo.png"
paper_normal = "paper/CC0-Texture-Paper01/PaperNormal.png"
paper_roughness = "paper/CC0-Texture-Paper01/PaperRough.png"
